name: obmin
description: Obmin library
version: 0.1.0
repository: https://github.com/prokhor-andrew/obmin-dart.git
homepage: https://github.com/prokhor-andrew/obmin-dart.git

environment:
  sdk: ^3.9.2

dependencies:
  fast_immutable_collections: ^11.0.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
